// <auto-generated />
using System;
using HalisahaApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HalisahaApp.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260502064650_IlkMigrasyon")]
    partial class IlkMigrasyon
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HalisahaApp.API.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Adminler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdSoyad = "Halısaha Yöneticisi",
                            Email = "admin@halisaha.com",
                            OlusturmaTarihi = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SifreHash = "$2a$11$example_hash_buraya_gelecek"
                        });
                });

            modelBuilder.Entity("HalisahaApp.API.Models.Rezervasyon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BaslangicSaati")
                        .HasColumnType("int");

                    b.Property<int>("BitisSaati")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IptalNedeni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("IptalTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("IyzicoOdemeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OdemeDurumu")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SahaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ToplamUcret")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SahaId", "Tarih", "BaslangicSaati")
                        .IsUnique();

                    b.ToTable("Rezervasyonlar");
                });

            modelBuilder.Entity("HalisahaApp.API.Models.Saha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcilisSaati")
                        .HasColumnType("int");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int>("KapanisSaati")
                        .HasColumnType("int");

                    b.Property<int>("NakitDeadlineGun")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SaatlikUcret")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SahaKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("SahaKodu")
                        .IsUnique();

                    b.ToTable("Sahalar");
                });

            modelBuilder.Entity("HalisahaApp.API.Models.Rezervasyon", b =>
                {
                    b.HasOne("HalisahaApp.API.Models.Saha", "Saha")
                        .WithMany("Rezervasyonlar")
                        .HasForeignKey("SahaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Saha");
                });

            modelBuilder.Entity("HalisahaApp.API.Models.Saha", b =>
                {
                    b.HasOne("HalisahaApp.API.Models.Admin", "Admin")
                        .WithMany("Sahalar")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("HalisahaApp.API.Models.Admin", b =>
                {
                    b.Navigation("Sahalar");
                });

            modelBuilder.Entity("HalisahaApp.API.Models.Saha", b =>
                {
                    b.Navigation("Rezervasyonlar");
                });
#pragma warning restore 612, 618
        }
    }
}
